apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ozwt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ozwt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ozwt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ozwt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ozwt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jjob-tenant/rhtap-demo-app/hacbs-test-project-ozwt@sha256:f196cbda92338238821a79c3b5fa283287d7357d995c988eb952addd682a3328
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
