apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ozwt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jjob-tenant/rhtap-demo-app/hacbs-test-project-ozwt@sha256:f196cbda92338238821a79c3b5fa283287d7357d995c988eb952addd682a3328
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
